name: Python CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.1
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.1
    - name: Install dependencies
      run: |
        pip install .
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Check formatting with black
      run: |
        black --check
    - name: Test with pytest
      run: |
        pytest .
    - name: Check typehints with mypy
      run: |
        mypy .
